### PR TITLE
Fixes Bug

### PR DESCRIPTION
**Pull request by Cess-Uyi**
#### What does this PR do?
This PR fixes the bugs in the UI

#### Questions:
None

### CODE REVIEW

**Comment by oolushola** [comment]
Your PR isn't detailed enough. There is a reason why I said you always create a feature branch. Now, I can't explicitly tell what changes were made. Please raise the pull request again, detailing bugs that were fixed. All your commits should have been in different branches, instead of one.

**Review by oolushola — COMMENTED** [review]
Wow! You have over 61 file changes? This is too lengthy for me to review.

**Comment by Cess-Uyi** [comment]
#### What does this PR do?
This Pull Request fixes bugs in the UI such as
- color coordination
- reduction in font size
- improvement in the user experience by adding the side nav in every section of the user profile so they don't have to go back to the previous page

#### Any background context you want to provide?
There were certain aesthetic and functional issues Shola corrected so I worked on these corrections as bugs

#### What are the relevant pivotal tracker stories?
None. I didn't make a pivotal tracker story for the bugs

#### Questions:
None

**Comment by Cess-Uyi** [comment]
> Your PR isn't detailed enough. There is a reason why I said you always create a feature branch. Now, I can't explicitly tell what changes were made. Please raise the pull request again, detailing bugs that were fixed. All your commits should have been in different branches, instead of one.

I made a branch named bug

**Pull request merged**
